[pytest]
testpaths = tests/
bdd_features_base_dir = features/
addopts = --alluredir=allure-results
markers =
    setup: marks tests as setup phase tests
    registro: marks tests related to user registration
